### PR TITLE
feat: add angular 11.2 support

### PR DESCRIPTION
**Pull request by marcelpotirnac**
Current library version 4.1.1 works with angualr 11 until version 11.1.

From 11.2 it breaks with the following error.

``` js
core.js:6140 ERROR Error: Metadata not created 
 Maybe you forgot to import the NgxsDataPluginModule
 Also, you cannot use this.ctx.* until the application is fully rendered 
 (use by default ngxsOnInit(ctx: StateContext), or ngxsAfterBootstrap(ctx: StateContext) !!!
    at Function.ensureMappedState (ngxs-data-factory.service.ts:34)
    at PriceState.get [as context] (create-context.ts:15)
    at PriceState.get ctx [as ctx] (ngxs-data.repository.ts:22)
    at PriceState.getState (ngxs-data.repository.ts:26)
    at PriceState.get snapshot (ngxs-data.repository.ts:18)
    at PriceState.descriptor.get (computed.ts:24)
    at AmountComponent_Template (amount.component.html:2)
    at executeTemplate (core.js:9527)
    at refreshView (core.js:9396)
    at refreshComponent (core.js:10562)
```

Upgrading angular on library fixes the issue.

_used `ng update`_

### CODE REVIEW

**Comment by splincode** [comment]
good work!

**Comment by miguelvictor** [comment]
hi when will be the next release date (including this fix)?

**Comment by splincode** [comment]
hi, as soon as possible in the next week

**Comment by tsavo-vdb-knott** [comment]
Hello all - I have tried to download the repo and build internally and then use (we need this update badly). Nevertheless, it seems the even the master branch of this is failing to build.

Would love any suggestions :) Simply ran the ng build lib!

Best - T

Screen Shot 2021-03-23 at 2 35 00 PM

**Comment by marcelpotirnac** [comment]
That's strange @tsavo-vdb-knott , I just tried on a clean location and it builds the lib without any errors.
Using yarn with (node 15 arm and node 12 x64) macos

Do you mind sharing those details?

**Comment by tsavo-vdb-knott** [comment]
**So - First I Installed with Yarn**


Screen Shot 2021-03-23 at 3 20 51 PM

**Second I got a successful Install completion and Ran build:lib**


Screen Shot 2021-03-23 at 3 21 21 PM

**Lastly I got a failed**


Screen Shot 2021-03-23 at 3 22 23 PM

**Comment by tsavo-vdb-knott** [comment]
How can I be more helpful - Let me try it with node 12 @marcelpotirnac

**Comment by tsavo-vdb-knott** [comment]
OKAY ! So I used Node 12 and it worked!

Thats awesome :) !! I am going to try and use it internally now within our project.

**Comment by marcelpotirnac** [comment]
Sorry @tsavo-vdb-knott , I got distracted in the meantime, I am glad it worked out. Good luck! 

Here is some nice list of compatibility https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
